# ① 전처리 — 문서 파싱 · 청크 분할
담당: 전처리 · 코드: `rag/preprocessing/parsing.py`, `rag/preprocessing/chunking.py`

`config.yaml` 의 `paths.input`(ZIP 또는 폴더)에 있는 PDF · HWP · HWPX 를 읽어 본문 · 표 · (선택) 그림 설명을 뽑고, 청크로 나눕니다.

| 저장 파일 | 읽는 노트북 |
|---|---|
| `artifacts/chunks.jsonl` (청크) | 02 검색, 03 검증 |
| `artifacts/docs.jsonl` (문서 목록 — 발주기관 라우팅용) | 02 검색 |

## 설정
`OCR = True` 로 바꾸면 문서 속 그림을 OpenAI 비전 모델(`gpt-5-mini`, `.env` 의 `OPENAI_API_KEY`)로 글로 바꿔 청크에 넣습니다 (유료).
로고 · 장식처럼 여러 쪽에 반복되는 그림(`config.yaml` 의 `max_repeat_image_pages` 쪽 이상)은 청크에 넣지 않습니다.
`False` 면 그림은 API 로 보내지 않습니다.

In [6]:
OCR = True

In [7]:
from rag.config import ARTIFACTS, ROOT, load_config
from rag.preprocessing.chunking import chunk_documents, chunk_summary, save_chunks
from rag.preprocessing.parsing import collect_inputs, parse_documents, parsing_summary

cfg = load_config()

## 1. 입력 파일 모으기
ZIP(안의 ZIP 포함)을 `artifacts/raw/` 에 풀고 PDF · HWP · HWPX 목록을 만듭니다.

In [8]:
files = collect_inputs(ROOT / cfg["paths"]["input"], ARTIFACTS / "raw")
len(files)

98

## 2. 파싱
문서마다 쪽 · 표 · 그림 수와 표지 감지 결과를 봅니다.

In [9]:
docs = parse_documents(files, cfg["parsing"], ocr=OCR)
parsing_summary(docs)

(1/98) (사)벤처기업협회_2024년 벤처확인종합관리시스템 기능 고도화 용역사업 .hwp: 블록 299개
(2/98) (사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원시.hwp: 블록 155개
(3/98) (사）한국대학스포츠협의회_KUSF 체육특기자 경기기록 관리시스템 개발.hwp: 블록 205개
(4/98) (재)예술경영지원센터_통합 정보시스템 구축 사전 컨설팅.hwp: 블록 145개
(5/98) 2025 구미 아시아육상경기선수권대회 조직위원회_2025 구미아시아육상경.hwp: 블록 133개
(6/98) BioIN_의료기기산업 종합정보시스템(정보관리기관) 기능개선 사업(2차).hwp: 블록 207개
(7/98) KOICA 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원 .hwp: 블록 281개
(8/98) 경기도 안양시_호계체육관 배드민턴장 및 탁구장 예약시스템 구축 용역.hwp: 블록 176개
(9/98) 경기도 평택시_2024년도 평택시 버스정보시스템(BIS) 구축사업.hwp: 블록 192개
(10/98) 경기도사회서비스원_2024년 통합사회정보시스템 운영지원.hwp: 블록 163개
(11/98) 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급).hwp: 블록 163개
(12/98) 경희대학교_[입찰공고] 산학협력단 정보시스템 운영 용역업체 선정.hwp: 블록 81개
(13/98) 고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf: 블록 1031개
(14/98) 고양도시관리공사_관산근린공원 다목적구장 홈페이지 및 회원 통합운영.hwp: 블록 191개
(15/98) 광주과학기술원_실시간통합연구비관리시스템(RCMS)  연계 모듈 변경 사업.hwp: 블록 157개
(16/98) 광주과학기술원_학사시스템 기능개선 사업.hwp: 블록 135개
(17/98) 국가과학기술지식정보서비스_통합정보시스템 고도화 용역.hwp: 블록 192개
(18/98) 국가철도공단_철도인프라 디지털트윈 정보화전략계획(ISP) 수립 용역(변.hwp: 블록 147개
(19/98) 국립인천해양박물관_국립인천해양박물관 해양자료관리시스템 구축 용.hwp: 블록 144개
(20/98) 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축.hwp: 블록 360개
(21/98) 국민연금공단_2024년 이러닝시스템 운영 용역.hwp: 블록 95개
(22/98) 국민연금공단_사업장 사회보험료 지원 고시 개정에 따른 정보시스템 보.hwp: 블록 126개
(23/98) 국방과학연구소_기록관리시스템 통합 활용 및 보안 환경 구축.hwp: 블록 156개
(24/98) 국방과학연구소_대용량 자료전송시스템 고도화.hwp: 블록 118개
(25/98) 그랜드코리아레저(주)_2024년도 GKL  그룹웨어 시스템 구축 용역.hwp: 블록 316개
(26/98) 기초과학연구원_2025년도 중이온가속기용 극저온시스템 운전 용역.pdf: 블록 126개
(27/98) 나노종합기술원_스마트 팹 서비스 활용체계 구축관련 설비온라인 시스.hwp: 블록 153개
(28/98) 남서울대학교_[혁신-국고] 남서울대학교 스마트 정보시스템 활성화(학사.hwp: 블록 200개
(29/98) 대검찰청_아태 사이버범죄 역량강화 허브(APC-HUB) 홈페이지 및 온라인 교.hwp: 블록 136개
(30/98) 대전대학교_대전대학교 2024학년도 다층적 융합 학습경험 플랫폼(MILE) 전.hwp: 블록 203개
(31/98) 대한상공회의소_기업 재생에너지 지원센터 홈페이지 개편 및 시스템 고.hwp: 블록 176개
(32/98) 대한장애인체육회_2025년 전국장애인체육대회 전산 및 시스템, 홈페이지 .hwp: 블록 167개
(33/98) 대한적십자사 의료원_적십자병원 병원정보 재해복구시스템 구축 용역 .hwp: 블록 131개
(34/98) 문화체육관광부 국립민속박물관_2024년 국립민속박물관 민속아카이브 자.hwp: 블록 188개
(35/98) 부산관광공사_경영정보시스템 기능개선.hwp: 블록 190개
(36/98) 사단법인 보험개발원_실손보험 청구 전산화 시스템 구축 사업.hwp: 블록 204개
(37/98) 사단법인아시아물위원회사무국_우즈벡-키르기즈스탄 기후변화대응 스.hwp: 블록 129개
(38/98) 서민금융진흥원_서민금융진흥원 서민금융 채팅 상담시스템 구축.hwp: 블록 203개
(39/98) 서영대학교 산학협력단_전문대학 혁신지원사업 서영대학교 차세대 교육.hwp: 블록 268개
(40/98) 서울시립대학교_[사전공개] 학업성취도 다차원 종단분석 통합시스템 1차.pdf: 블록 338개
(41/98) 서울특별시 여성가족재단_(재공고, 협상) 서울 디지털성범죄 안심지원센.hwp: 블록 267개
MuPDF error: syntax error: invalid key in dict

MuPDF error: syntax error: invalid key in dict

(42/98) 서울특별시_2024년 지도정보 플랫폼 및 전문활용 연계 시스템 고도화 용.pdf: 블록 272개
(43/98) 서울특별시교육청_서울특별시교육청 지능정보화전략계획(ISP) 수립(2차) .hwp: 블록 126개
(44/98) 세종테크노파크_세종테크노파크 인사정보 전산시스템 구축 용역 입찰공.hwp: 블록 172개
(45/98) 수협중앙회_강릉어선안전조업국 상황관제시스템 구축.hwp: 블록 177개
(46/98) 수협중앙회_수협중앙회 수산물사이버직매장 시스템 재구축 ISMP 수립 입.hwp: 블록 159개
(47/98) 울산광역시_2024년 버스정보시스템 확대 구축 및 기능개선 용역.hwp: 블록 220개
(48/98) 을지대학교_을지대학교 비교과시스템 개발.hwp: 블록 145개
(49/98) 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 ERP시스템 구축 .hwp: 블록 185개
(50/98) 인천광역시 동구_수도국산달동네박물관 전시해설 시스템 구축(협상에 .hwp: 블록 196개
(51/98) 인천광역시_도시계획위원회 통합관리시스템 구축용역.hwp: 블록 177개
(52/98) 인천광역시_인천일자리플랫폼 정보시스템 구축 ISP 수립용역.hwp: 블록 160개
(53/98) 재단법인 광주광역시 광주문화재단_2024년 광주문화예술통합플랫폼 시스.hwp: 블록 151개
(54/98) 재단법인 광주연구원_광주정책연구아카이브(GPA) 시스템 개발.hwp: 블록 210개
(55/98) 재단법인 한국장애인문화예술원_2024년 장애인문화예술정보시스템 이음.hwp: 블록 135개
(56/98) 재단법인경기도일자리재단_2025년 통합접수시스템 운영.hwp: 블록 236개
(57/98) 재단법인스포츠윤리센터_스포츠윤리센터 LMS(학습지원시스템) 기능개선.hwp: 블록 195개
(58/98) 재단법인충북연구원_GIS통계 기반 재난안전데이터 분석ㆍ관리 시스템 구.hwp: 블록 137개
(59/98) 전북대학교_JST 공유대학(원) xAPI기반 LRS시스템 구축.hwp: 블록 139개
(60/98) 전북특별자치도 정읍시_정읍체육트레이닝센터 통합운영관리시스템 구.hwp: 블록 242개
(61/98) 조선대학교_(재공고)2024 조선대학교 SW중심대학 사업관리시스템(WeHub) 구.hwp: 블록 98개
(62/98) 중앙선거관리위원회_2025년도 행정정보시스템 위탁운영사업.hwp: 블록 246개
(63/98) 축산물품질평가원_꿀 품질평가 전산시스템 기능개선 사업.hwp: 블록 207개
(64/98) 축산물품질평가원_축산물이력관리시스템 개선(정보화 사업).hwp: 블록 207개
(65/98) 케빈랩 주식회사_평택시 강소형 스마트시티 AI 기반의 영상감시 시스템 .hwp: 블록 209개
(66/98) 파주도시관광공사_종량제봉투 판매관리 전산시스템 개선사업.hwp: 블록 231개
(67/98) 한국가스공사_[재공고]차세대 통합정보시스템(ERP) 구축.hwp: 블록 204개
(68/98) 한국건강가정진흥원_2025년 아이돌봄인력 인적성 검사 정보시스템 운영.hwp: 블록 182개
(69/98) 한국교육과정평가원_국가교육과정정보센터(NCIC) 시스템 운영 및 개선.hwp: 블록 123개
(70/98) 한국농수산식품유통공사_농산물가격안정기금 정부예산회계연계시스템 .hwp: 블록 174개
(71/98) 한국농어촌공사_네팔 수자원관리 정보화사업-Pilot 시스템 구축용역.hwp: 블록 168개
(72/98) 한국농어촌공사_아세안+3 식량안보정보시스템(AFSIS) 3단계 협력(캄보디아.hwp: 블록 274개
(73/98) 한국로봇산업진흥원_한국로봇산업진흥원 사업관리시스템 온라인평가 .hwp: 블록 119개
(74/98) 한국발명진흥회 입찰공고_2024년 건설기술에 관한 특허·실용신안 활용실.hwp: 블록 200개
(75/98) 한국보육진흥원_연차별 자율 품질관리 시스템 기능개선.hwp: 블록 195개
(76/98) 한국사학진흥재단_대학재정정보시스템(기본재산 및 기채 사후관리) 고.hwp: 블록 230개
(77/98) 한국사회보장정보원_라오스 보건의료정보화 협력을 위한 사전타당성 조.hwp: 블록 113개
(78/98) 한국산업단지공단_산단 안전정보시스템 1차 구축 용역.hwp: 블록 236개
(79/98) 한국산업인력공단_RFID기반 국가자격 시험 결과물 스마트 관리시스템 도.hwp: 블록 127개
(80/98) 한국생산기술연구원_2세대 전자조달시스템  기반구축사업.hwp: 블록 177개
(81/98) 한국생산기술연구원_EIP3.0 고압가스 안전관리 시스템 구축 용역.hwp: 블록 227개
(82/98) 한국수자원공사_건설통합시스템(CMS) 고도화.hwp: 블록 168개
(83/98) 한국수자원공사_수도사업장 통합 사고분석솔루션 시범구축 용역.hwp: 블록 138개
(84/98) 한국수자원공사_용인 첨단 시스템반도체 국가산단 용수공급사업 타당성.hwp: 블록 18개
(85/98) 한국수자원조사기술원_수문자료정보관리시스템(HDIMS) 재구축 용역(3단계.hwp: 블록 177개
(86/98) 한국수출입은행_(긴급) 모잠비크 마푸토 지능형교통시스템(ITS) 구축사업.hwp: 블록 153개
(87/98) 한국어촌어항공단_한국어촌어항공단 경영관리시스템(ERP·GW) 기능 고도.hwp: 블록 216개
(88/98) 한국연구재단_2024년 기초학문자료센터 시스템 운영 및 연구성과물 DB구.hwp: 블록 163개
(89/98) 한국연구재단_2024년 대학산학협력활동 실태조사 시스템(UICC) 기능개선.hwp: 블록 201개
(90/98) 한국원자력연구원_한국원자력연구원 선량평가시스템 고도화.hwp: 블록 137개
(91/98) 한국재정정보원_e나라도움 업무시스템 웹 접근성 컨설팅.hwp: 블록 146개
(92/98) 한국전기안전공사_전기안전 관제시스템 보안 모듈 개발 용역.hwp: 블록 122개
(93/98) 한국지식재산보호원_IP-NAVI  해외지식재산센터 사업관리 시스템 기능개.hwp: 블록 127개
(94/98) 한국철도공사 (용역)_[재공고][긴급][협상형]운행정보기록 자동분석시스.hwp: 블록 241개
(95/98) 한국철도공사 (용역)_모바일오피스 시스템 고도화 용역(총체 및 1차).hwp: 블록 308개
(96/98) 한국철도공사 (용역)_예약발매시스템 개량 ISMP 용역.hwp: 블록 186개
(97/98) 한국해양조사협회_2024년 항해용 간행물 품질관리 업무보조 시스템 구축.hwp: 블록 142개
(98/98) 한영대학_한영대학교 특성화 맞춤형 교육환경 구축 - 트랙운영 학사정보.hwp: 블록 163개

,문서,형식,text,table,image_caption,글자 수
0,(사)벤처기업협회_2024년 벤처확인종합관리시스템 기능 고도화 용역사업 .hwp,hwp,77,214,8.0,123438
1,(사)부산국제영화제_2024년 BIFF & ACFM 온라인서비스 재개발 및 행사지원...,hwp,39,101,15.0,63490
2,(사）한국대학스포츠협의회_KUSF 체육특기자 경기기록 관리시스템 개발.hwp,hwp,58,142,5.0,87305
3,(재)예술경영지원센터_통합 정보시스템 구축 사전 컨설팅.hwp,hwp,56,83,6.0,55480
4,2025 구미 아시아육상경기선수권대회 조직위원회_2025 구미아시아육상경.hwp,hwp,50,83,0.0,54417
...,...,...,...,...,...,...
93,한국철도공사 (용역)_[재공고][긴급][협상형]운행정보기록 자동분석시스.hwp,hwp,84,152,5.0,126292
94,한국철도공사 (용역)_모바일오피스 시스템 고도화 용역(총체 및 1차).hwp,hwp,80,224,4.0,156272
95,한국철도공사 (용역)_예약발매시스템 개량 ISMP 용역.hwp,hwp,71,107,8.0,88022
96,한국해양조사협회_2024년 항해용 간행물 품질관리 업무보조 시스템 구축.hwp,hwp,60,75,7.0,70770
97,한영대학_한영대학교 특성화 맞춤형 교육환경 구축 - 트랙운영 학사정보.hwp,hwp,55,108,0.0,48604

## 3. 청크 분할 · 저장

In [10]:
chunks = chunk_documents(docs, cfg["chunking"])
save_chunks(docs, chunks, ARTIFACTS)
chunk_summary(chunks)

    청크 수  text  table  image_caption  평균 길이  중앙값  문장 중간 절단(%)  섹션 부착(%)
0  18630  4994  12620           1016  469.9  442         45.1      93.9